// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jwI6GO27s0uUvGHX9R3eQ80nTSN1fuE',
    appId: '1:240074680330:web:0b13139a1887ec0d6257f3',
    messagingSenderId: '240074680330',
    projectId: 'chat-app-1cf34',
    authDomain: 'chat-app-1cf34.firebaseapp.com',
    storageBucket: 'chat-app-1cf34.appspot.com',
    measurementId: 'G-NY9P1Q1R68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPtaCWFLw0zPX5_DN219MfRDiOeVJIEQ',
    appId: '1:240074680330:android:afffd736710d4f096257f3',
    messagingSenderId: '240074680330',
    projectId: 'chat-app-1cf34',
    storageBucket: 'chat-app-1cf34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtze-lBj8WABZn4R9UJINAnQonE2_EX1M',
    appId: '1:240074680330:ios:632c60f271163e1b6257f3',
    messagingSenderId: '240074680330',
    projectId: 'chat-app-1cf34',
    storageBucket: 'chat-app-1cf34.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtze-lBj8WABZn4R9UJINAnQonE2_EX1M',
    appId: '1:240074680330:ios:632c60f271163e1b6257f3',
    messagingSenderId: '240074680330',
    projectId: 'chat-app-1cf34',
    storageBucket: 'chat-app-1cf34.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-jwI6GO27s0uUvGHX9R3eQ80nTSN1fuE',
    appId: '1:240074680330:web:e81d63b88527506c6257f3',
    messagingSenderId: '240074680330',
    projectId: 'chat-app-1cf34',
    authDomain: 'chat-app-1cf34.firebaseapp.com',
    storageBucket: 'chat-app-1cf34.appspot.com',
    measurementId: 'G-QV4FYRN4QH',
  );
}
